version: '3.9'

services:
  postgres-bankcards:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - ./postgres-bankcards:/data/postgres-bankcards

  bankcards:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres-bankcards
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS}
      APP_JWT_CLOCK_SKEW_SECONDS: ${APP_JWT_CLOCK_SKEW_SECONDS}
      APP_BANK_CARD_ENCRYPTION_BASE64_KEY: ${APP_BANK_CARD_ENCRYPTION_BASE64_KEY}
      APP_BANK_CARD_BANK_BIN: ${APP_BANK_CARD_BANK_BIN}
