spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-bankcards:5432/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS}
    clock-skew-seconds: ${APP_JWT_CLOCK_SKEW_SECONDS}
  bank-card:
    encryption:
      base64-key: ${APP_BANK_CARD_ENCRYPTION_BASE64_KEY}
    bank-bin: ${APP_BANK_CARD_BANK_BIN}
